version: "3.9"

services:
  jupyterlab:
    image: "ghcr.io/uw-gda/uwgda-image-living:latest"
    ports:
      - "8888:8888"
    command: "jupyter lab --ip 0.0.0.0 --no-browser"
    volumes:
      - ${PWD}:/home/jovyan/
